import type { CSSProperties } from "react";

export const userManagementStyles: Record<string, CSSProperties> = {
  userMgmtTop: { display: "flex", gap: "16px", marginBottom: "20px", alignItems: "center", flexWrap: "wrap" },
  totalCard: { background: "#fff", borderRadius: "14px", padding: "16px 24px", border: "1px solid #F0D9C8", minWidth: "150px" },
  totalLabel: { fontSize: "11px", color: "#9B7355", fontWeight: 700, letterSpacing: "0.06em", textTransform: "uppercase" },
  totalValue: { fontSize: "28px", fontWeight: 800, color: "#3B1A00", fontFamily: "'Manrope', sans-serif" },
  filterRow: { display: "flex", gap: "8px", alignItems: "center", flexWrap: "wrap" },
  filterLabel: { fontSize: "11px", fontWeight: 700, color: "#9B7355", letterSpacing: "0.06em", textTransform: "uppercase" },
  searchWrap: { position: "relative", marginBottom: "16px" },
  searchIcon: { position: "absolute", left: "14px", top: "50%", transform: "translateY(-50%)", color: "#9B7355", fontSize: "15px" },
  searchInput: {
    width: "100%", padding: "11px 14px 11px 40px", borderRadius: "10px",
    border: "1.5px solid #F0D9C8", background: "#fff",
    fontSize: "14px", color: "#3B1A00",
    fontFamily: "'Manrope', sans-serif",
  },
  bulkBar: {
    padding: "12px 16px",
    borderBottom: "1px solid #F0D9C8",
    display: "flex",
    alignItems: "center",
  },
  bulkShowing: { fontSize: "13px", color: "#9B7355" },
  requestsCard: {
    background: "#fff",
    borderRadius: "16px",
    border: "1.5px solid #FBBF24",
    marginBottom: "20px",
    overflow: "hidden",
  },
  requestsHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "14px 20px",
    borderBottom: "1px solid #FEF3C7",
    background: "#FFFBEB",
  },
  requestsTitle: {
    fontSize: "14px",
    fontWeight: 800,
    color: "#92400E",
    fontFamily: "'Manrope', sans-serif",
    letterSpacing: "-0.01em",
  },
  requestsBadge: {
    background: "#F59E0B",
    color: "#fff",
    borderRadius: "50px",
    padding: "1px 8px",
    fontSize: "12px",
    fontWeight: 700,
    fontFamily: "'Manrope', sans-serif",
  },
  requestsList: { display: "flex", flexDirection: "column" },
  requestRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 20px",
    borderBottom: "1px solid #FEF3C7",
    gap: "12px",
  },
  requestUser: { display: "flex", alignItems: "center", gap: "12px", minWidth: 0, flex: 1 },
  requestName: { fontSize: "14px", fontWeight: 700, color: "#3B1A00", fontFamily: "'Manrope', sans-serif" },
  requestEmail: { fontSize: "12px", color: "#9B7355", fontFamily: "'Manrope', sans-serif" },
  requestDate: { fontSize: "11px", color: "#C8A882", fontFamily: "'Manrope', sans-serif", marginTop: "2px" },
  requestActions: { display: "flex", gap: "8px", flexShrink: 0 },
  requestsEmpty: { padding: "16px 20px", fontSize: "13px", color: "#9B7355", fontFamily: "'Manrope', sans-serif" },
  approveBtn: {
    padding: "6px 14px", borderRadius: "8px", border: "none",
    background: "#DC2626", color: "#fff",
    fontSize: "12px", fontWeight: 700, cursor: "pointer",
    fontFamily: "'Manrope', sans-serif", transition: "background 0.15s ease",
  },
  rejectBtn: {
    padding: "6px 14px", borderRadius: "8px",
    border: "1px solid #E7C9B6", background: "#fff0e7", color: "#9B7355",
    fontSize: "12px", fontWeight: 700, cursor: "pointer",
    fontFamily: "'Manrope', sans-serif", transition: "background 0.15s ease",
  },
  unlockBtn: {
    padding: "5px 12px", borderRadius: "8px", border: "1.5px solid #D97706",
    background: "#F59E0B", color: "#fff",
    fontSize: "12px", fontWeight: 700, cursor: "pointer",
    transition: "background 0.15s ease",
    fontFamily: "'Manrope', sans-serif",
  },
  deactivatedTag: {
    marginLeft: "6px", padding: "1px 7px", borderRadius: "50px",
    background: "#FEE2E2", color: "#DC2626",
    fontSize: "10px", fontWeight: 700,
    fontFamily: "'Manrope', sans-serif", verticalAlign: "middle",
  },
  pendingTag: {
    marginLeft: "6px", padding: "1px 7px", borderRadius: "50px",
    background: "#FEF3C7", color: "#92400E",
    fontSize: "10px", fontWeight: 700,
    fontFamily: "'Manrope', sans-serif", verticalAlign: "middle",
  },
  lockedTag: {
    marginLeft: "6px", padding: "1px 7px", borderRadius: "50px",
    background: "#EDE9FE", color: "#5B21B6",
    fontSize: "10px", fontWeight: 700,
    fontFamily: "'Manrope', sans-serif", verticalAlign: "middle",
  },
};